apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: staging
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "122e49da-0d28-4d34-88e3-3ae8dd5d04d2"
    keyvaultName: "kv-boutique-635"
    objects:  |
      array:
        - |
          objectName: redis-password
          objectType: secret
  secretObjects:
    - secretName: redis-secret
      type: Opaque
      data:
        - objectName: redis-password
          key: REDIS_PASSWORD